/***********************************************************************
 * Permission is hereby granted to any individual or institution       *
 * for use, copying, or redistribution of the AV2XGobi C code          *
 * and associated documentation, provided such code and documentation  *
 * are not sold for profit and the following copyright notice is       *
 * retained in the code and documentation:                             *
 *                                                                     *
 *   Copyright (c) 1995, 1996, 1997 Iowa State University              *
 *                                                                     *
 * We encourage you to share questions, comments and modifications.    *
 *                                                                     *
 *   Juergen Symanzik (symanzik@iastate.edu)                           *
 *   Dianne Cook (dicook@iastate.edu)                                  *
 *   James J. Majure (majure@iastate.edu)                              *
 *                                                                     *
 * The code in this file was generated by ESRI, using rpcgen.          *
 * It has been modified to provide the functionality required for      *
 * the AV2XGOBI link.                                                  *
 *                                                                     *
 ***********************************************************************/

/* @(#)aiserver_svc_proc.c	1.1 4/28/94 10:19:35 */

#ifdef RPC_USED

#include <string.h>
#include <stdlib.h>
#include <signal.h>
#include <rpc/rpc.h>
#include "rpc_server.h"

/* this block of includes just for Brush_Realloc */
#include "xincludes.h"
#include <X11/keysym.h>
#include "xgobitypes.h"
#include "xgobivars.h"
#include "rpc_xgobi.h"

static strngrec Str;
static strngrec *Strptr;
static char *chbuff = NULL;


void chbuff_resize (size)

int size;

{
  static int lastsize = 0;

  if (size > lastsize) /* do we have enough memory? */
  {
    lastsize = size;
    chbuff = (char *) XtRealloc ((char *) chbuff, (Cardinal) size);
  }

/* originally:
	Str.retstr = (char *)chbuff;
   now:
	Str.retstr = chbuff;
*/
}


strngrec *procedure1_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function1 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure2_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function2 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure3_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function3 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure4_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function4 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure5_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function5 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure6_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function6 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure7_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function7 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure8_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function8 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure9_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function9 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure10_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function10 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure11_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function11 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure12_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function12 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure13_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function13 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure14_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function14 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure15_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function15 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure16_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function16 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure17_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function17 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure18_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function18 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure19_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function19 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure20_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function20 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure21_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function21 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure22_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function22 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure23_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function23 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure24_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function24 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure25_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function25 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure26_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function26 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure27_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function27 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure28_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function28 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure29_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function29 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure30_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function30 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure31_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function31 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure32_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function32 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure33_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function33 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure34_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function34 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure35_1 (instr)
char **instr;
{
        chbuff_resize (xgobi.nrows_in_plot * 20);
	Function35 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure36_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function36 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure37_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function37 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure38_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function38 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure39_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function39 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure40_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function40 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure41_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function41 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure42_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function42 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure43_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function43 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure44_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function44 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure45_1 (instr)
char **instr;
{
        chbuff_resize (xgobi.nrows_in_plot * 20);
	Function45 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure46_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function46 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure47_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function47 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure48_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function48 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure49_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function49 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure50_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function50 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure51_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function51 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure52_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function52 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure53_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function53 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure54_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function54 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure55_1 (instr)
char **instr;
{
        chbuff_resize (xgobi.nrows_in_plot * 20);
	Function55 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure56_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function56 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure57_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function57 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure58_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function58 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure59_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function59 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure60_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function60 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure61_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function61 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure62_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function62 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure63_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function63 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure64_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function64 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure65_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function65 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure66_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function66 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure67_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function67 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure68_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function68 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure69_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function69 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure70_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function70 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure71_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function71 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure72_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function72 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure73_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function73 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure74_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function74 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure75_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function75 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure76_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function76 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure77_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function77 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure78_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function78 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure79_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function79 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure80_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function80 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure81_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function81 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure82_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function82 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure83_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function83 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure84_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function84 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure85_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function85 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure86_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function86 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure87_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function87 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure88_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function88 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure89_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function89 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure90_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function90 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure91_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function91 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure92_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function92 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure93_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function93 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure94_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function94 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure95_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function95 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure96_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function96 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure97_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function97 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure98_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function98 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
strngrec *procedure99_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	Function99 (*instr,chbuff);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}
void quitfn ()
{
 extern unsigned long server_prognum;
 extern unsigned long server_vernum;

	svc_unregister (server_prognum, server_vernum);
	exit (0);
}

strngrec *quit_1 (instr)
char **instr;
{
        chbuff_resize (1024);
	strcpy (chbuff," ");
        signal (SIGALRM, quitfn);
	alarm (1);
	Str.retstr = chbuff;
	Strptr = &Str;
	return ((strngrec *) Strptr);
}

#endif
