/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef xgobi_goes_dce_v1_0_included
#define xgobi_goes_dce_v1_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
extern void RPC_Send_Colnames(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Rownames(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Clone_XGobi(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Xfer_Colornames(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Init_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Make_XGobi(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Update_All_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Update_Some_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Init_CDF_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_CDF_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_CDF_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Make_CDF_XGobi(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Add_CDF_Bitmap(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Add_CDF_Type(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Delete_CDF_Bitmap_and_Type(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Brush_All_CDF_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_CDF_Weights(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Init_VARIO_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_VARIO_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_VARIO_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Make_VARIO_XGobi(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Update_Some_VARIO_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[10000]
#endif
);
extern void RPC_Init_LAG_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_LAG_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_LAG_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Make_LAG_XGobi(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Update_Some_LAG_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[10000]
#endif
);
extern void RPC_Send_LAG_Colnames(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Init_VARIO2_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_VARIO2_Data(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Send_Init_VARIO2_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Make_VARIO2_XGobi(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
extern void RPC_Update_Some_VARIO2_Symbols(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[10000]
#endif
);
globalref handle_t xgobi_server_binding_handle;
typedef struct xgobi_goes_dce_v1_0_epv_t {
void (*RPC_Send_Colnames)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Rownames)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Clone_XGobi)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Xfer_Colornames)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Init_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Make_XGobi)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Update_All_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Update_Some_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Init_CDF_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_CDF_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_CDF_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Make_CDF_XGobi)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Add_CDF_Bitmap)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Add_CDF_Type)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Delete_CDF_Bitmap_and_Type)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Brush_All_CDF_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_CDF_Weights)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Init_VARIO_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_VARIO_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_VARIO_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Make_VARIO_XGobi)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Update_Some_VARIO_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[10000]
#endif
);
void (*RPC_Init_LAG_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_LAG_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_LAG_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Make_LAG_XGobi)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Update_Some_LAG_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[10000]
#endif
);
void (*RPC_Send_LAG_Colnames)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Init_VARIO2_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_VARIO2_Data)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Send_Init_VARIO2_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Make_VARIO2_XGobi)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[100]
#endif
);
void (*RPC_Update_Some_VARIO2_Symbols)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr,
    /* [out] */ idl_char outstr[10000]
#endif
);
} xgobi_goes_dce_v1_0_epv_t;
extern rpc_if_handle_t xgobi_goes_dce_v1_0_c_ifspec;
extern rpc_if_handle_t xgobi_goes_dce_v1_0_s_ifspec;

#ifdef __cplusplus
    }

#else
#endif
#endif
