/* Generated by IDL compiler version OSF DCE T1.2.0-09 */
#ifndef xgobi_dceclient_v1_0_included
#define xgobi_dceclient_v1_0_included
#ifndef IDLBASE_H
#include <dce/idlbase.h>
#endif
#include <dce/rpc.h>

#ifdef __cplusplus
    extern "C" {
#endif

#ifndef nbase_v0_0_included
#include <dce/nbase.h>
#endif
extern void Xfer_Brushinfo(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr
#endif
);
globalref handle_t xgobi_client_binding_handle;
typedef struct xgobi_dceclient_v1_0_epv_t {
void (*Xfer_Brushinfo)(
#ifdef IDL_PROTOTYPES
    /* [in] */ idl_char *instr
#endif
);
} xgobi_dceclient_v1_0_epv_t;
extern rpc_if_handle_t xgobi_dceclient_v1_0_c_ifspec;
extern rpc_if_handle_t xgobi_dceclient_v1_0_s_ifspec;

#ifdef __cplusplus
    }

#else
#endif
#endif
